version: "2"

services:
  voting-app:
    image: clabs/voting-app
    ports:
      - "80"
    environment:
      - REDIS_HOST=redis
      - constraint:tier==1

  result-app:
    image: clabs/result-app
    ports:
      - "80"
    environment:
      - DB_HOST=db

  worker:
    image: clabs/worker
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db

  redis:
    image: redis
    expose:
      - "6379"
    environment:
      - constraint:provider==digitalocean

  db:
    image: postgres:9.4
    environment:
      - constraint:provider==digitalocean
